= Universal Segmentations

This repository servers as the main storage of scripts and documentation
of the Universal Segmentations project, which aims to convert existing
resources for morphological segmentation into a common format and, in
the future, to develop new resources.


== API

A Python API for working with morphological segmentation is available
in link:src/useg/seg_lex.py[].

NOTE: TODO Add documentation.

* Document setting the PYTHONPATH
* Document importing and creating the lexicon
* Document creating new lexemes
* Document working with lexemes
** Getting form, lemma, POS tag, other morphological info
** Deleting lexemes
** Changing morphological info
** What to do when we need to change the lemma or POS (A: Create a new lexeme instead and delete the old one.)
** Getting lexemes by lemma, form, pos etc. (not implemented yet)
* Document basic concepts of morphemes
** They are bound to the form of the lexeme
** Spans index, where in the form is the morph of the morpheme located
** Ideally, each lexeme has its form perfectly subdivided between morphemes with no gaps nor overlap
*** But you don't need to fully segment the word if you don't know all the morphemes
*** And edge cases (overlaps – morfémové uzly) are supported too
** Each lexeme can have multiple alternative segmentations
*** These are distinguished using annotation layer names
* Document creating new morphemes (contiguous or not)
* Document deleting morphemes (not implemented yet)
* Document morpheme properties; what are you expected to fill out
** And how to query and obtain the properties
